# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo pipenv --python 3.6
            pipenv install --skip-lock
            pipenv install --skip-lock --dev
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pwd
            ls
            sudo pipenv run "flake8 numeronym --exclude=numeronym/resources/* --statistics"
            sudo pipenv run "pytest -v --cov=numeronym"
