# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo pipenv --python 3.6
            pipenv install --skip-lock
            pipenv install --skip-lock --dev
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            cd numeronym
            ls
            # sudo pipenv run "flake8 numeronym --exclude=numeronym/resources/* --statistics"
            # sudo pipenv run "pytest -v --cov=numeronym"
            sudo pipenv run "pytest -s . -p '*_test.py'"